In [ ]:
from numpy import random
import numpy as np

In [ ]:
def isSubsetSum(set, n, sum,count):
     
    # The value of subset[i][j] will be 
    # true if there is a
    count=0
    # subset of set[0..j-1] with sum equal to i
    subset =([[False for i in range(sum + 1)] 
            for i in range(n + 1)])
    count+=5
     
    # If sum is 0, then answer is true 
    for i in range(n + 1):
        subset[i][0] = True
        count+=1
        count+=2
    # If sum is not 0 and set is empty, 
    # then answer is false 
    for i in range(1, sum + 1):
         subset[0][i]= False
         count+=2 
         count+=1      
    # Fill the subset table in botton up manner
    for i in range(1, n + 1):
        count+=2
        for j in range(1, sum + 1):
            count+=2
            if j<set[i-1]:
                subset[i][j] = subset[i-1][j]
                count+=2
            if j>= set[i-1]:
                count+=2
                count+=2
                subset[i][j] = (subset[i-1][j] or
                                subset[i - 1][j-set[i-1]])
                count+=6
    # uncomment this code to print table 
    # for i in range(n + 1):
    # for j in range(sum + 1):
    # print (subset[i][j], end =" ")
    # print()
    # return subset[n][sum]
    return count

In [ ]:
c=0
arrN=[]
arrC=[]
for i in range (0,50):
    S=random.randint(1000)
    val=random.randint(100,size=(random.randint(1,50)))
    n=len(val)
    arrN.append(n*S)
    arrC.append(isSubsetSum(val,n,S,c))

dic = {'n*sum': arrN , 'T(n*sum)': arrC}

In [ ]:
val=random.randint(100,size=(random.randint(1,50)))
print(val)

[71 83 96 18 20  5 21 15 85 93 14 47 62]

In [ ]:
import pandas as pd
data = pd.DataFrame.from_dict(dic)
print(data)

    n*sum  T(n*sum)
0    9720    111475
1    8892    103147
2   38520    447569
3    9594    108673
4   20832    245921
5   11808    137690
6      60       332
7    6764     68300
8   38661    448320
9    7150     83611
10   1872     21486
11   6838     78635
12   6923     82670
13  14784    170992
14   6996     70177
15    123       886
16  20088    228206
17    396      2089
18  11725    131936
19    516      5627
20   4060     43748
21   8932    105112
22  16659    190334
23   9443    106710
24  12768    150534
25  29088    330650
26   9918    114101
27   6512     71190
28  26136    307007
29   6272     65924
30  16192    187075
31   7527     86262
32  33600    386764
33  41184    478022
34   3880     39002
35   1102      7909
36   4544     53008
37   6030     65887
38  24531    279038
39   6462     72223
40   5863     67254
41  28017    323484
42   6305     71988
43  19600    228568
44  11328    131256
45   1166      8517
46    222      2749
47   2538     19385
48    855     10266
49  28247    322170

In [ ]:
data_sorted = data.sort_values(by=['n*sum', 'T(n*sum)'])
data_sorted

    n*sum  T(n*sum)
6      60       332
15    123       886
46    222      2749
17    396      2089
19    516      5627
48    855     10266
35   1102      7909
45   1166      8517
10   1872     21486
47   2538     19385
34   3880     39002
20   4060     43748
36   4544     53008
40   5863     67254
37   6030     65887
29   6272     65924
42   6305     71988
39   6462     72223
27   6512     71190
7    6764     68300
11   6838     78635
12   6923     82670
14   6996     70177
9    7150     83611
31   7527     86262
1    8892    103147
21   8932    105112
23   9443    106710
3    9594    108673
0    9720    111475
26   9918    114101
44  11328    131256
18  11725    131936
5   11808    137690
24  12768    150534
13  14784    170992
30  16192    187075
22  16659    190334
43  19600    228568
16  20088    228206
4   20832    245921
38  24531    279038
28  26136    307007
41  28017    323484
49  28247    322170
25  29088    330650
32  33600    386764
2   38520    447569
8   38661    448320
33  41184    478022

In [ ]:
data_sorted.to_csv('./data.csv', index=False)

In [ ]:
df = pd.read_csv('/content/data.csv')
df

    n*sum  T(n*sum)
0      60       332
1     123       886
2     222      2749
3     396      2089
4     516      5627
5     855     10266
6    1102      7909
7    1166      8517
8    1872     21486
9    2538     19385
10   3880     39002
11   4060     43748
12   4544     53008
13   5863     67254
14   6030     65887
15   6272     65924
16   6305     71988
17   6462     72223
18   6512     71190
19   6764     68300
20   6838     78635
21   6923     82670
22   6996     70177
23   7150     83611
24   7527     86262
25   8892    103147
26   8932    105112
27   9443    106710
28   9594    108673
29   9720    111475
30   9918    114101
31  11328    131256
32  11725    131936
33  11808    137690
34  12768    150534
35  14784    170992
36  16192    187075
37  16659    190334
38  19600    228568
39  20088    228206
40  20832    245921
41  24531    279038
42  26136    307007
43  28017    323484
44  28247    322170
45  29088    330650
46  33600    386764
47  38520    447569
48  38661    448320
49  41184    478022

Tính độ phức tạp

In [ ]:
df_cal = df.copy()
df_cal["lg(n*sum)"] = np.log2(df_cal["n*sum"])
df_cal["sqrt(n*sum)"] = np.sqrt(df_cal["n*sum"])
df_cal["n*sum"] = df_cal["n*sum"]
df_cal["(n*sum)lg(n*sum)"] = df_cal["n*sum"] * np.log2(df_cal["n*sum"])
df_cal["(n*sum)^2"] = df_cal["n*sum"]**2
df_cal["(n*sum)^3"] = df_cal["n*sum"]**3
df_cal["2^(n*sum)"] = [2**int(i) for i in df_cal["n*sum"]]
df_cal["(n*sum)!"] = np.array([(np.math.factorial(int(i)))for i in df_cal["n*sum"]])
df_cal.to_csv("data_cal.csv")

In [ ]:
df_cal

    n*sum  ...                                           (n*sum)!
0      60  ...  8320987112741390144276341183223364380754172606...
1     123  ...  1214630436702532967576624324188129585545421708...
2     222  ...  1120507558006441391828246578742885033161823448...
3     396  ...  2539263159807035946064767087756565867327655771...
4     516  ...  2436566677748420523803949181961053300467322489...
5     855  ...  2367889249307504668308110954418455384810441125...
6    1102  ...  6483532196019773510840007614429756178455348882...
7    1166  ...  2068302906174795100024273398818398978307071119...
8    1872  ...  6202014640616277868268862441548532173469117583...
9    2538  ...  2895214891440398712277107157133155148509381894...
10   3880  ...  6280882161940725892766962636907056359699651798...
11   4060  ...  3832319078826498370813968836227495783986394706...
12   4544  ...  1561096154908565262640608846629576848803885805...
13   5863  ...  3173571305979736315850631869939396689693285959...
14   6030  ...  6410928312726864071472908281219405898872791057...
15   6272  ...  5414418268703479814220035179359376132033899508...
16   6305  ...  1221034687242321831814930655174082329114861487...
17   6462  ...  3052049995418400699388588947643281359639844273...
18   6512  ...  1225762875427706746084917828238345571316226333...
19   6764  ...  1751719740166410659547009299574668194497533856...
20   6838  ...  7178837422079327626603697415502259871303059902...
21   6923  ...  1138156170938394415861477146498250018715680643...
22   6996  ...  3685793975208639040613451115513980829866911313...
23   7150  ...  2563901203794240821768583986638710845847823351...
24   7527  ...  5445056676222110861414931279553953251252403414...
25   8892  ...  1349602441458969990559690405620044226030733707...
26   8932  ...  1349500341633480633117619083971394444357072207...
27   9443  ...  2029965961091820117397348174932563276407669241...
28   9594  ...  1186018725000422605396789473263554942609887497...
29   9720  ...  1467769212412341706482299524100572982190348233...
30   9918  ...  3970974930961421248355503212840067312037411903...
31  11328  ...  1535272197144200091252014803904855153504576270...
32  11725  ...  4775640701397515238508116856477209154662430298...
33  11808  ...  3501180213417947994049267622089638169564639078...
34  12768  ...  2275435775273219908223861203142990408660192613...
35  14784  ...  1198433677332800412935515698656697159406443276...
36  16192  ...  2518309277194808578102841935457055696540136814...
37  16659  ...  1115930888448248017906152264365950648220325680...
38  19600  ...  3911768089134034455979362694877844214411328580...
39  20088  ...  6845911562440808572149868671181041610269499106...
40  20832  ...  1378200360651372567061318271841980182928934673...
41  24531  ...  1049232784129643917599067223337774168571360494...
42  26136  ...  7060094720391230253979346805149506270963815008...
43  28017  ...  2547496999681945451837827282547811762057608999...
44  28247  ...  5293596455371856489148024939126572622341176306...
45  29088  ...  2409145541206423598415784531918649405040662740...
46  33600  ...  2330177473497514796560013088569181639668144350...
47  38520  ...  2013432571089898587002056658075830354478971176...
48  38661  ...  9963997549610909348261698823633543347189273820...
49  41184  ...  5036110020816621700341034815424087543498848184...

[50 rows x 9 columns]

In [ ]:
# n*sum	T(n*sum)	lg(n*sum)	sqrt(n*sum)	(n*sum)lg(n*sum)	(n*sum)^2	(n*sum)^3
data_cop = df_cal[['n*sum',	'T(n*sum)',	'lg(n*sum)',	'sqrt(n*sum)',	'(n*sum)lg(n*sum)',	'(n*sum)^2',	'(n*sum)^3']].copy()
data_cop.to_csv('data_cropped.csv')
data_cop

    n*sum  T(n*sum)  lg(n*sum)  ...  (n*sum)lg(n*sum)   (n*sum)^2       (n*sum)^3
0      60       332   5.906891  ...        354.413436        3600          216000
1     123       886   6.942515  ...        853.929284       15129         1860867
2     222      2749   7.794416  ...       1730.360322       49284        10941048
3     396      2089   8.629357  ...       3417.225222      156816        62099136
4     516      5627   9.011227  ...       4649.793264      266256       137388096
5     855     10266   9.739781  ...       8327.512421      731025       625026375
6    1102      7909  10.105909  ...      11136.711176     1214404      1338273208
7    1166      8517  10.187352  ...      11878.452517     1359556      1585242296
8    1872     21486  10.870365  ...      20349.322755     3504384      6560206848
9    2538     19385  11.309476  ...      28703.450986     6441444     16348384872
10   3880     39002  11.921841  ...      46256.742836    15054400     58411072000
11   4060     43748  11.987264  ...      48668.291889    16483600     66923416000
12   4544     53008  12.149747  ...      55208.450911    20647936     93824221184
13   5863     67254  12.517423  ...      73389.653051    34374769    201539270647
14   6030     65887  12.557942  ...      75724.391989    36360900    219256227000
15   6272     65924  12.614710  ...      79119.460142    39337984    246727835648
16   6305     71988  12.622281  ...      79583.479531    39753025    250642822625
17   6462     72223  12.657765  ...      81794.477658    41757444    269836603128
18   6512     71190  12.668885  ...      82499.779018    42406144    276148809728
19   6764     68300  12.723661  ...      86062.842628    45751696    309464471744
20   6838     78635  12.739359  ...      87111.734841    46758244    319732872472
21   6923     82670  12.757182  ...      88317.968444    47927929    331805052467
22   6996     70177  12.772315  ...      89355.112759    48944016    342412335936
23   7150     83611  12.803728  ...      91546.651815    51122500    365525875000
24   7527     86262  12.877859  ...      96931.646621    56655729    426447672183
25   8892    103147  13.118292  ...     116647.854536    79067664    703069668288
26   8932    105112  13.124768  ...     117230.423630    79780624    712600533568
27   9443    106710  13.205030  ...     124695.094088    89170249    842034661307
28   9594    108673  13.227917  ...     126908.633052    92044836    883078156584
29   9720    111475  13.246741  ...     128758.318617    94478400    918330048000
30   9918    114101  13.275834  ...     131669.716752    98366724    975601168632
31  11328    131256  13.467606  ...     152561.035671   128323584   1453649559552
32  11725    131936  13.517300  ...     158490.346044   137475625   1611901703125
33  11808    137690  13.527477  ...     159732.448488   139428864   1646376026112
34  12768    150534  13.640245  ...     174158.647346   163021824   2081462648832
35  14784    170992  13.851749  ...     204784.257828   218566656   3231289442304
36  16192    187075  13.982994  ...     226412.631961   262180864   4245232549888
37  16659    190334  14.024014  ...     233626.052246   277522281   4623243679179
38  19600    228568  14.258566  ...     279467.894264   384160000   7529536000000
39  20088    228206  14.294046  ...     287138.802341   403527744   8106065321472
40  20832    245921  14.346514  ...     298866.574089   433972224   9040509370368
41  24531    279038  14.582318  ...     357718.853302   601769961  14762018913291
42  26136    307007  14.673751  ...     383513.149326   683090496  17853253203456
43  28017    323484  14.774015  ...     413923.574414   784952289  21992008280913
44  28247    322170  14.785810  ...     417654.775985   797893009  22538083825223
45  29088    330650  14.828136  ...     431320.834052   846111744  24611698409472
46  33600    386764  15.036174  ...     505215.433382  1128960000  37933056000000
47  38520    447569  15.233320  ...     586787.489587  1483790400  57155606208000
48  38661    448320  15.238591  ...     589139.179569  1494672921  57785549798781
49  41184    478022  15.329796  ...     631342.332393  1696121856  69853082517504

[50 rows x 7 columns]

Linear Coefficient

In [ ]:
dt = pd.read_csv('/content/data.csv')
dt.columns = ['size', 'operations']

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
# lg(n*W)
X_1 = np.log2(dt['size'])
X_1 = X_1.values.reshape(-1,1)
regr = LinearRegression()
regr.fit(X_1, dt['operations'])
co2 = float(regr.coef_)
print(co2)

46417.5299670394

In [ ]:
# sqrt(n*W)
X_2 = dt['size'].values.reshape(-1,1)
X_2 = X_2**(1/2)
regr = LinearRegression()

regr.fit(X_2, dt['operations'])
co1 = float(regr.coef_)
# print(float(regr.coef_))
print(co1)

2413.16618484437

In [ ]:
# n*W
X_3 = dt['size'].values.reshape(-1,1)
regr = LinearRegression()
regr.fit(X_3,dt['operations'])
co3 = float(regr.coef_)
print(co3)

11.642716760229987

In [ ]:
# (n*W)lg(n*W)
n = np.round(np.log2(dt['size']).values.reshape(-1,1))
X_4 = np.round(dt['size'].values.reshape(-1,1))
X_4 = X_4 * n
regr = LinearRegression()
regr.fit(X_4, dt['operations'])
co4 = float(regr.coef_)
print(co4)

0.7644205037016568

In [ ]:
# (n*W)^2
X_5 = dt['size'].values.reshape(-1,1)
X_5 = X_5**2
regr = LinearRegression()

regr.fit(X_5, dt['operations'])
co5 = float(regr.coef_)
print(co5)

0.000290397549531241

In [ ]:
# (n*W)^3
X_6 = dt['size'].values.reshape(-1,1)
X_6 = X_6**3
regr = LinearRegression()
regr.fit(X_6, dt['operations'])
co6 = float(regr.coef_)
print(co6)

7.177599446158811e-09

Driver code

In [ ]:
# n*sum	T(n*sum)	lg(n*sum)	sqrt(n*sum)	(n*sum)lg(n*sum)	(n*sum)^2	(n*sum)^3
data_coef = data_cop.copy()
data_coef["lg(n*sum)*{}".format(co1)] = data_coef["lg(n*sum)"] * co1
data_coef["sqrt(n*sum)*{}".format(co2)] = data_coef["sqrt(n*sum)"] * co2
data_coef["n*sum*{}".format(co3)] = data_coef["n*sum"] * co3
data_coef["(n*sum)lg(n*sum)*{}".format(co4)] = data_coef["(n*sum)lg(n*sum)"] * co4
data_coef["(n*sum)^2*{}".format(co5)] = data_coef["(n*sum)^2"] * co5
data_coef["(n*sum)^3*{}".format(co6)] = data_coef["(n*sum)^2"] * co6

In [ ]:
data_coef

    n*sum  ...  (n*sum)^3*7.177599446158811e-09
0      60  ...                         0.000026
1     123  ...                         0.000109
2     222  ...                         0.000354
3     396  ...                         0.001126
4     516  ...                         0.001911
5     855  ...                         0.005247
6    1102  ...                         0.008717
7    1166  ...                         0.009758
8    1872  ...                         0.025153
9    2538  ...                         0.046234
10   3880  ...                         0.108054
11   4060  ...                         0.118313
12   4544  ...                         0.148203
13   5863  ...                         0.246728
14   6030  ...                         0.260984
15   6272  ...                         0.282352
16   6305  ...                         0.285331
17   6462  ...                         0.299718
18   6512  ...                         0.304374
19   6764  ...                         0.328387
20   6838  ...                         0.335612
21   6923  ...                         0.344007
22   6996  ...                         0.351301
23   7150  ...                         0.366937
24   7527  ...                         0.406652
25   8892  ...                         0.567516
26   8932  ...                         0.572633
27   9443  ...                         0.640028
28   9594  ...                         0.660661
29   9720  ...                         0.678128
30   9918  ...                         0.706037
31  11328  ...                         0.921055
32  11725  ...                         0.986745
33  11808  ...                         1.000765
34  12768  ...                         1.170105
35  14784  ...                         1.568784
36  16192  ...                         1.881829
37  16659  ...                         1.991944
38  19600  ...                         2.757347
39  20088  ...                         2.896361
40  20832  ...                         3.114879
41  24531  ...                         4.319264
42  26136  ...                         4.902950
43  28017  ...                         5.634073
44  28247  ...                         5.726956
45  29088  ...                         6.073051
46  33600  ...                         8.103223
47  38520  ...                        10.650053
48  38661  ...                        10.728164
49  41184  ...                        12.174083

[50 rows x 13 columns]

In [ ]:
data_coef.to_csv('data_final.csv')

In [ ]:
data_pow = df_cal[['2^(n*sum)', 'T(n*sum)']].copy()
data_pow.to_csv('data_pow.csv')
data_pow

                                            2^(n*sum)  T(n*sum)
0                                 1152921504606846976       332
1              10633823966279326983230456482242756608       886
2   6739986666787659948666753771754907668409286105...      2749
3   1613906173804317868534949482501882421456066120...      2089
4   2145249268790815535931843999712935380396698531...      5627
5   2402405385217504073590770462562962195619763069...     10266
6   5433194116197543397109405713437067114413975387...      7909
7   1002247413642806386229778738695466628040881172...      8517
8   3374052865751378554842782751275541741289475461...     21486
9   1033068204581562946560944850433183977906350909...     19385
10  9917065376376886325280797525846631169751988761...     39002
11  1519785846777307606959588462947612253745267297...     43748
12  7591022822348516345400634964334321364566334806...     53008
13  8686895115402092838413073742001916105201257842...     67254
14  1625076663613693637168969190154224127027336638...     65887
15  1148504773258281776942352511564517662440165330...     65924
16  9865580880888431186240341828946130308389755306...     71988
17  1802320326329861712039071620223274271497274847...     72223
18  2029232287515358989231163200781862886210016490...     71190
19  1468556538245135769073873807100984724771635748...     68300
20  2774024869763161367976241176512082459376976282...     78635
21  1073148892579134338920568630564547282794958340...     82670
22  1013560472288876266541665678423985684494445268...     70177
23  2314562952787618622652167044545234645372561886...     83611
24  7124876859975222766579029743574472756018849142...     86262
25  5737483427718643983865717072307464462077512363...    103147
26  6308429742948750284843624059174253343054117841...    105112
27  4229110716649699674416867764086930280095076297...    106710
28  1207197702507266466262594096205703863639744055...    108673
29  1026970228876728906439631709044151002753229084...    111475
30  4125693827758445921456341693012873133690698968...    114101
31  1168936397462879067046066300098001308901325808...    131256
32  3773107337299836992636785396688275645022277805...    131936
33  3649125504191341226953871042690123760280289782...    137690
34  3556187390535296372968609964209024848559925084...    150534
35  2675813843744081004200910964316376928375676092...    170992
36  1895351621673122625923415599068914413821421954...    187075
37  7222669894161542382365519967111001505612519517...    190334
38  1541398791075480030412687437633673634082170014...    228568
39  1231836017023667908847513662188320703166923190...    228206
40  1139907659993701289679359898634928314681323912...    245921
41  3688277872835784440150450618123221703171250847...    279038
42  5247671899688804975937052177218967530071973628...    307007
43  9065432274774012500871127886038431714099955919...    323484
44  1564182852112470280688106160544295557412672356...    322170
45  2293579899523848492524938789526333048824437556...    330650
46  4053725246844196441698240575762384955670801193...    386764
47  4736232095980785679329775965487285526481093905...    447569
48  1320268814669626696154903665886134201951463823...    448320
49  4162377117723936543148785848457483582967564763...    478022

In [ ]:
# 2^(n*W)
dpow = pd.read_csv('/content/drive/MyDrive/subset sum/data_pow.csv')
dpow.columns = ['size','operations']
dpow['size'] = dpow['size'].astype('float')

X_7 = dpow['operations'].values.reshape(-1,1)
regr = LinearRegression()
regr.fit(X_7, dpow['operations'])
co7 = regr.coef_
print(co7)

[1.]

In [ ]:
data_fac = df_cal[['(n*sum)!', 'T(n*sum)']].copy()
data_fac.to_csv('data_fac.csv')
data_fac

                                             (n*sum)!  T(n*sum)
0   8320987112741390144276341183223364380754172606...       332
1   1214630436702532967576624324188129585545421708...       886
2   1120507558006441391828246578742885033161823448...      2749
3   2539263159807035946064767087756565867327655771...      2089
4   2436566677748420523803949181961053300467322489...      5627
5   2367889249307504668308110954418455384810441125...     10266
6   6483532196019773510840007614429756178455348882...      7909
7   2068302906174795100024273398818398978307071119...      8517
8   6202014640616277868268862441548532173469117583...     21486
9   2895214891440398712277107157133155148509381894...     19385
10  6280882161940725892766962636907056359699651798...     39002
11  3832319078826498370813968836227495783986394706...     43748
12  1561096154908565262640608846629576848803885805...     53008
13  3173571305979736315850631869939396689693285959...     67254
14  6410928312726864071472908281219405898872791057...     65887
15  5414418268703479814220035179359376132033899508...     65924
16  1221034687242321831814930655174082329114861487...     71988
17  3052049995418400699388588947643281359639844273...     72223
18  1225762875427706746084917828238345571316226333...     71190
19  1751719740166410659547009299574668194497533856...     68300
20  7178837422079327626603697415502259871303059902...     78635
21  1138156170938394415861477146498250018715680643...     82670
22  3685793975208639040613451115513980829866911313...     70177
23  2563901203794240821768583986638710845847823351...     83611
24  5445056676222110861414931279553953251252403414...     86262
25  1349602441458969990559690405620044226030733707...    103147
26  1349500341633480633117619083971394444357072207...    105112
27  2029965961091820117397348174932563276407669241...    106710
28  1186018725000422605396789473263554942609887497...    108673
29  1467769212412341706482299524100572982190348233...    111475
30  3970974930961421248355503212840067312037411903...    114101
31  1535272197144200091252014803904855153504576270...    131256
32  4775640701397515238508116856477209154662430298...    131936
33  3501180213417947994049267622089638169564639078...    137690
34  2275435775273219908223861203142990408660192613...    150534
35  1198433677332800412935515698656697159406443276...    170992
36  2518309277194808578102841935457055696540136814...    187075
37  1115930888448248017906152264365950648220325680...    190334
38  3911768089134034455979362694877844214411328580...    228568
39  6845911562440808572149868671181041610269499106...    228206
40  1378200360651372567061318271841980182928934673...    245921
41  1049232784129643917599067223337774168571360494...    279038
42  7060094720391230253979346805149506270963815008...    307007
43  2547496999681945451837827282547811762057608999...    323484
44  5293596455371856489148024939126572622341176306...    322170
45  2409145541206423598415784531918649405040662740...    330650
46  2330177473497514796560013088569181639668144350...    386764
47  2013432571089898587002056658075830354478971176...    447569
48  9963997549610909348261698823633543347189273820...    448320
49  5036110020816621700341034815424087543498848184...    478022

In [ ]:
# (n*W)!
dfac = pd.read_csv('/content/drive/MyDrive/subset sum/data_fac.csv')

dfac.columns = ['size','operations']
dfac['size'] = dfac['size'].astype('float')

X_8 = dfac['operations'].values.reshape(-1,1)
regr = LinearRegression()
regr.fit(X_8, dfac['operations'])
co8 = regr.coef_
print(co8)

ValueError: ignored